### ISSUE TITLE
Warning on install

### ISSUE THREAD

**Issue by hugodes** [turt2live/node-email-reply-parser#12]
I get this error upon installation:

> npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install 
> peer  dependencies yourself.

Should we add ajv-keywords to the dependencies ? Or is it more an issue with ajv-keywords ?

**Comment by turt2live** [comment]
I'm sure it's required somewhere deep in the dependency graph, although I'm failing to find it at a quick glance. 

Assuming the tests pass, this should be okay without it though. I'll keep this open to double check more in depth though.

**Comment by turt2live** [comment]
I'm going to assume that time has fixed this issue. If not, please open a new issue.
