### ISSUE TITLE
Error while trying minify

### ISSUE THREAD

**Issue by danhruby** [turt2live/node-email-reply-parser#14]
Failed to minify the code from this file:

 	./node_modules/node-email-reply-parser/lib/Parser.js:53

Read more here: http://bit.ly/2tRViJ9

Is it possible to pre-compiled package?

**Comment by turt2live** [comment]
What about minifying the module failed? Also, what tool is doing the minifying and how?

**Comment by turt2live** [comment]
I'm going to assume this has been resolved in the last few years. If not, please open a new issue.
