### ISSUE TITLE
Is there any support for parsing html email?

### ISSUE THREAD

**Issue by manojchowdary27** [turt2live/node-email-reply-parser#16]

**Comment by turt2live** [comment]
You'll need to be more descriptive. HTML isn't really a concern for this kind of library

**Comment by manojchowdary27** [comment]
Sorry. Let me explain this more clearly.
I have sent a **plain text email** to another person.
There is a possibility that they can reply **with images or some html formatted email**.
Now I have to parse the exact reply with images and styles, by ignoring my email text.

Is this making sense?

**Comment by turt2live** [comment]
The library works by finding the various "In reply to..." strings that clients leave behind, so it should be fine.

**Comment by manojchowdary27** [comment]
I created the test scenario with this issue. Can you check this once.

https://runkit.com/manojchowdary27/runkit-npm-node-email-reply-parser

**Comment by turt2live** [comment]
Sorry, I don't have much time these days to troubleshoot every issue with this library. If there's a bug, please open a PR to fix it so others can benefit.
