### ISSUE TITLE
Port french regex change

### ISSUE THREAD

**Issue by turt2live** [turt2live/node-email-reply-parser#19]
https://github.com/willdurand/EmailReplyParser/pull/73

**Comment by glensc** [comment]
@turt2live would you mind sending PR to origin project that you have node port?

**Comment by turt2live** [comment]
That's the plan, but I am wrapped up in about a million things right now. Anyone is more than welcome to submit a PR here and I'd be happy to send the release machine going.

**Comment by glensc** [comment]
you mis undestood me, I meant that you send PR to willdurand/EmailReplyParser that you maintain nodejs port here.

**Comment by turt2live** [comment]
PRing the whole project? Not sure that's the best idea... There's nothing different in this repo.

**Comment by glensc** [comment]
What? I mean to spread information, send PR there that this project exists.

If you don't understand me, then leave it.

**Comment by turt2live** [comment]
Ah, okay. Sorry, having a hard time keeping track of things these days. Will definitely make a PR when I get a chance: https://github.com/turt2live/node-email-reply-parser/issues/20
